import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChangeEvent, useReducer } from 'react'
import styles from '../styles/Home.module.css'
import round from '../utils/round'
import { ACTION } from '../types/_types'
import { initialState, reducer } from '../utils/state'
import { choixNicotine, pgvgChoices } from '../utils/globals'

const Home: NextPage = () => {
  const [state, dispatch] = useReducer(reducer, initialState)
  const onChange = (type:ACTION) => (e:ChangeEvent<HTMLInputElement | HTMLSelectElement>) => dispatch({ type, value: parseFloat(e.target.value) })

  return (
    <div className={styles.container}>
      <Head>
        <title>DIY VAPING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>DIY VAPING</h1>

        <div>
          <label htmlFor="pgvg">PG/VG</label>
          <select name="pgvg" value={state?.pgvg} onChange={onChange(ACTION.CHANGE_PGVG)}>
              {pgvgChoices.map(pgvg => (
                <option key={pgvg.base} value={pgvg.dosage}>{pgvg.visuel}</option>
              ))
              }
          </select>
        </div>

        <div>
          <label htmlFor="nictotine">Nicotine</label>
          <select value={state?.nicotine} name="nictotine" onChange={onChange(ACTION.CHANGE_NICOTINE)}>
              {choixNicotine.map(nicotine => (
                <option key={`nictoine-${nicotine}`} value={nicotine}>{nicotine}</option>
              ))
              }
          </select>
        </div>

        <div>
          <label htmlFor="base">Base</label>
          <input type="number" name='base' value={round(state?.base)} step={1} onChange={onChange(ACTION.CHANGE_BASE)}/>
        </div>

        <div>
          <label htmlFor="booster">Booster</label>
          <input type="number" name='booster' value={round(state?.booster)} readOnly />
        </div>

        <div className=''>
          <label htmlFor="arome">Arome</label>
          <input type="number" name='arome' value={round(state?.arome)} onChange={onChange(ACTION.CHANGE_AROME)}/>
        </div>

        <div className=''>
          <label htmlFor="liquide">Liquide</label>
          <input type="number" name='liquide' value={round(state?.liquide)} onChange={onChange(ACTION.CHANGE_LIQUIDE)}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home